### ISSUE TITLE
https for redirect_to_login

### ISSUE THREAD

**Issue by christopherreay** [ludia/pyramid_google_login#2]
Hi,

my whole server runs as https, but the redirect to login function redirects to http

What should I do?

thanks
Christopher

**Comment by christopherreay** [comment]
I think there is smiddle wear I removed that will sort it out.. I will check now

**Comment by hadrien** [comment]
Hi Christopher,
All urls are created using pyramid API (request.route_url): therefore, it should output https if request.method is https.
